### ISSUE TITLE
Tracking issue: synchronous exceptions in JS API

### ISSUE THREAD

**Issue by kainino0x** [webgpu-native/webgpu-headers#225]
I'll attempt to make a complete list of entrypoints that have synchronous exceptions in the JS API:

*   [x] All cases where you try to use a feature that's not enabled on the device that would throw a TypeError on a browser that hasn't implemented the feature at all ([see spec](https://gpuweb.github.io/gpuweb/#features))
    *   Using an enum value introduced by the feature (e.g. query type "timestamp")
    *   Calling a method introduced by the feature (e.g. writeTimestamp)
*   [x] getMappedRange: not mapped; not aligned; out of range; overlaps (#64)
*   [x] createBuffer with mappedAtCreation (OOM-ish conditions) (#57)
*   [ ] external image stuff (copyExternalImageToTexture/importExternalTexture) (not in C API yet, #232):
    *   "origin-clean" and "check the usability" of external image sources
    *   copyExternalImageToTexture source image size check (can be checked in the bindings beforehand so it’s possible to know what the error is, except maybe for HTMLVideoElement because it’s weird and frames advance in the background)
*   [x] writeBuffer: size alignment. Maybe this should be a validation error in the upstream spec?
*   [x] getCurrentTexture: not configured. See #197, maybe we need an extra GetCurrentTextureStatus for this?
*   [x] Things that can't happen from C
    *   Invalid extent/origin/color arrays
    *   Errors about the size of a source BufferSource in writeBuffer/writeTexture/setBindGroup
*   [x] (EDIT 2024-10-18) Invalid formats for configure() - this was recently moved from device timeline to content timeline in the JS spec.

One approach we've been taking for some entrypoints is to say "return a generic error code, with implementation-defined logging" (eventually we're likely to make it well-defined, with a log callback on the instance):

- CreateInstance/GetInstanceFeatures https://github.com/webgpu-native/webgpu-headers/issues/199#issuecomment-1701569747
- GetMappedRange https://github.com/webgpu-native/webgpu-headers/issues/64#issuecomment-1710774712.

**Comment by kainino0x** [comment]
Note this is **in addition to** synchronous errors from the C API that don't exist in the JS API (like #115).

**Comment by kainino0x** [comment]
*   Using features that aren’t enabled
    *   KN: propose injecting an error
    *   **OK!**
*   getCurrentTexture when not configured
    *   KN: Add a new status and return it? 
    *   (discussion) Return with a null texture?
    *   **Add a new status and return null texture (not error texture, WASM wouldn't be able to do that)**
*   writeBuffer size alignment
    *   **Inject an error, then we don’t care what the JS API does**

**Comment by kainino0x** [comment]
Marking "has resolution", we can figure out #232 when we get to it

**Comment by kainino0x** [comment]
One new addition (handled in #377):
- [ ] Invalid formats for configure() - this was recently moved from device timeline to content timeline in the JS spec.

**Comment by kainino0x** [comment]
I handled that in #377 by making it also a device error in webgpu.h (like formats not supported by the surface, and formats not supported by the device)
