### ISSUE TITLE
Tracking issue to write spec / explainers for native-specific parts of webgpu.h

### ISSUE THREAD

**Issue by Kangz** [webgpu-native/webgpu-headers#25]
Most of the behavior of webgpu.h is the same as the WebGPU API (normative reference) but there's a couple places where webgpu.h has non-trivial differences with WebGPU, and it also has native-specific APIs. This is a tracking issue to create initial explainers / spec for these parts.

Things that are very different in native:
 - [x] #24: surface creation and swapchains
 - [x] ~Instance / adapters and device creation~
     _not very different anymore_
 - [x] ~Event loop~ _Futures_
     _Covered in `Asynchronous Operations.md`_
 - [x] #9: lifetime management
     _`Ownership.md` probably sufficient_

Things that use callbacks (_Futures_) instead of promises:
_should be sufficiently covered in `Asynchronous Operations.md`_
 - [x] Buffer mapping
 - [x] Error reporting
 - [x] Device loss
 - [x] ~Fence~
     _doesn't exist anymore_

Other:
 - [x] `WGPUBindGroupBindingDescriptor` (no sum types in C)
     _will get documented with #438 / #403_
 - [x] How the regular part of webgpu.h relates the the WebGPU IDL
   _#452_
   _but could use more docs still; tracked in:_
   _#484_
 - [x] #160 How to make holes in WebGPU sparse arrays that are plain C arrays.

_2024-11-27: updates from @kainino0x in italics_

- [ ] _All items in the ["needs docs"](https://github.com/webgpu-native/webgpu-headers/issues?q=label%3A%22needs+docs%22) label (regardless of whether open or closed)_

**Comment by kainino0x** [comment]
I've created a new "needs docs" label which I'll try to add to everything that we're going to need to write docs/spec for. https://github.com/webgpu-native/webgpu-headers/labels/needs%20docs

**Comment by kainino0x** [comment]
I didn't go through the closed issues though. There may be some which still need documentation and should have the label added.

**Comment by kainino0x** [comment]
See discussion here https://github.com/webgpu-native/webgpu-headers/pull/275#issuecomment-2028627334 about having a "doc jam" to get the docs written

**Comment by kainino0x** [comment]
Apr 11 meeting:

*   doc jam - how should we do this?
*   KN: add links to spec in yaml?
    *   pull text from it at codegen time? (but the names will differ)
    *   or just generate links to the spec?
*   **Generator pulling from spec is worth exploring - from html**
*   **Explore having the spec repo itself generate some parseable (e.g. json) documentation out of the spec, similar to what types generator does today — then use this for both typescript and C**

**Comment by kainino0x** [comment]
We still want to fill out the docs for everything (see last comment).

The last item from the OP:

> [ ] How the regular part of webgpu.h relates the the WebGPU IDL
> _[State that webgpu.h has the same behavior as the JS spec #452](https://github.com/webgpu-native/webgpu-headers/pull/452)_

has a partial fix in #452, but ideally we should eventually write a doc that explains the patterns used to translate WebIDL to C.

However! I am going to call both of these things `non-blocking` for 1.0 and label this issue as such.

**Comment by kainino0x** [comment]
Last item is now tracked in #484 instead!
